/*
===============================================================================
Report: Product Category Performance
Project: Northwind Sales Analytics

Business Question:
Which product categories generate the highest revenue and sales volume
across all historical orders?

Report Grain:
One row per product category.

Business Rules:
- Revenue is calculated after discounts using the sales_reporting model.
- Total Revenue represents the sum of all product sales within each category.
- Units Sold represents the total quantity sold across all products
  within each category.
- Total Orders counts distinct orders containing products from the category.
- Categories are ranked by total historical revenue.
===============================================================================
*/

WITH product_category_performance AS (

    SELECT
        category_name,

        -- Total revenue generated by each product category.
        ROUND(SUM(revenue), 2) AS total_revenue,

        -- Number of unique orders containing products from the category.
        COUNT(DISTINCT order_id) AS total_orders,

        -- Total quantity of units sold across all products in the category.
        SUM(quantity) AS units_sold

    FROM sales_reporting

    GROUP BY
        category_name
)

SELECT

    category_name,
    total_revenue,
    units_sold,
    total_orders,

    -- Rank categories by total historical revenue.
    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank

FROM product_category_performance

ORDER BY total_revenue DESC;