/*
===============================================================================
Report: Product Revenue Distribution
Project: Northwind Sales Analytics

Business Question:
How is total revenue distributed across Northwind's product portfolio?

Report Grain:
One row per product.

Business Rules:
- Revenue is calculated after discounts using the sales_reporting model.
- Revenue Percentage represents each product's contribution to total revenue.
- Cumulative Revenue Percentage shows the running contribution of products
  ordered by revenue.
- Products are ranked by total historical revenue.
===============================================================================
*/

WITH product_metrics AS (

    SELECT
        product_id,
        product_name,
        category_name,

        -- Total revenue generated by each product.
        ROUND(SUM(revenue), 2) AS total_revenue,

        -- Number of unique orders containing the product.
        COUNT(DISTINCT order_id) AS total_orders,

        -- Total quantity of units sold.
        SUM(quantity) AS units_sold

    FROM sales_reporting

    GROUP BY
        product_id,
        product_name,
        category_name
),

product_revenue_distribution AS (

    SELECT
        product_id,
        product_name,
        category_name,
        total_revenue,
        total_orders,
        units_sold,

        -- Percentage contribution to total company revenue.
        ROUND(
            (total_revenue * 100.0)
            / SUM(total_revenue) OVER (),
            2
        ) AS revenue_percentage

    FROM product_metrics
)

SELECT
    product_id,
    product_name,
    category_name,
    total_revenue,
    total_orders,
    units_sold,
    revenue_percentage,

    -- Running percentage contribution ordered by revenue.
    ROUND(
        SUM(revenue_percentage) OVER (
            ORDER BY total_revenue DESC
        ),
        2
    ) AS cumulative_revenue_percentage,

    -- Rank products by total historical revenue.
    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank

FROM product_revenue_distribution

ORDER BY total_revenue DESC;