/*
===============================================================================
Report 08: Employee Performance Analysis
===============================================================================
Business Question:
    How has each employee contributed to company sales across all historical
    orders?

Business Objective:
    Evaluate employee sales performance to identify top-performing sales
    representatives, recognize high contributors, and uncover opportunities
    for coaching and performance improvement.

Report Grain:
    One row per employee.

Data Sources:
    - sales_reporting (Reusable reporting model)
    - employees

Business Metrics:
    - Total Revenue
    - Total Orders
    - Customers Served
    - Units Sold
    - Average Order Value
    - Revenue Rank

Business Rules:
    - Revenue is calculated after discounts using the sales_reporting model.
    - Total Orders counts distinct orders handled by each employee.
    - Customers Served counts distinct customers assigned to each employee.
    - Units Sold represents the total quantity of products sold.
    - Average Order Value = Total Revenue / Total Orders.
    - Employees are ranked by Total Revenue using DENSE_RANK().
===============================================================================
*/

With employee_metrics AS(

	SELECT
			employee_id,	
		 -- Total revenue generated by each employee.
        SUM(revenue) AS total_revenue,

        -- Number of unique orders handled by each employee.
        COUNT(DISTINCT order_id) AS total_orders,

        -- Number of unique customers served by each employee.
		COUNT(DISTINCT customer_id) AS customers_served,
		
		-- Total quantity of units sold by each employee.
        SUM(quantity) AS units_sold
	
	FROM sales_reporting

	GROUP BY employee_id
)

SELECT

	CONCAT(
		e.first_name, ' ', e.last_name
	) AS employee_name,
	
	total_revenue,
	total_orders,
	customers_served,
	units_sold,

	total_revenue / total_orders
	 AS average_order_value,

	 DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
	

FROM employee_metrics em

INNER JOIN employees e

ON e.employee_id = em.employee_id


ORDER BY total_revenue DESC;


	







	