/*
===============================================================================
Report 09: Employee Customer Efficiency Analysis
===============================================================================
Business Question:
    How efficiently does each employee generate revenue from their customer
    portfolio?

Business Context:
    Understanding customer efficiency helps management evaluate how effectively
    each employee generates value from the customers they serve. Rather than
    focusing solely on total sales, this report measures customer productivity
    by comparing revenue and order activity relative to the size of each
    employee's customer portfolio.

Report Grain:
    One row per employee.

KPIs:
    - Customers Served
    - Total Orders
    - Total Revenue
    - Revenue per Customer
    - Orders per Customer

Data Source:
    sales_reporting

Methodology:
    This report uses the reusable sales_reporting view to aggregate historical
    sales activity by employee. Employee names are joined from the employees
    table after aggregation. Revenue per Customer and Orders per Customer are
    calculated using the aggregated business metrics from the CTE.

SQL Concepts Used:
    - SQL Views
    - Common Table Expressions (CTEs)
    - Aggregate Functions
    - INNER JOIN
    - COUNT(DISTINCT)
    - ROUND()
    - CONCAT()
    - ORDER BY
===============================================================================
*/

WITH portfolio_metrics AS (

    SELECT
        employee_id,

        -- Total revenue generated by each employee.
        SUM(revenue) AS total_revenue,

        -- Number of unique orders handled by each employee.
        COUNT(DISTINCT order_id) AS total_orders,

        -- Number of unique customers served by each employee.
        COUNT(DISTINCT customer_id) AS customers_served

    FROM sales_reporting

    GROUP BY employee_id
)

SELECT

    CONCAT(
        e.first_name, ' ', e.last_name
    ) AS employee_name,

    customers_served,

    total_orders,

    total_revenue,

    -- Average revenue generated per customer served.
    ROUND(total_revenue / customers_served, 2)
        AS revenue_per_customer,

    -- Average number of orders placed by each customer.
    ROUND(total_orders::numeric / customers_served, 2)
        AS orders_per_customer

FROM portfolio_metrics pm

INNER JOIN employees e
    ON e.employee_id = pm.employee_id

ORDER BY revenue_per_customer DESC;