/*
===============================================================================
Report: Top Customers Analysis
Project: Northwind Sales Analytics

Business Question:
Who are Northwind's top 10 customers based on total historical revenue?

Report Grain:
One row per customer.

Business Rules:
- Only customers with purchasing history are included.
- Revenue is calculated after discounts.
- Customers are ranked by total historical revenue.
===============================================================================
*/

-- Calculate customer-level metrics for each purchasing customer.
WITH customer_metrics AS (

    SELECT
        c.customer_id,
        c.company_name,
        c.country,

        -- Total revenue generated by the customer after discounts.
        ROUND(
            SUM((od.unit_price * od.quantity) * (1 - od.discount))::numeric,
            2
        ) AS total_revenue,

        -- Number of unique orders placed by the customer.
        COUNT(DISTINCT o.order_id) AS total_orders,

        -- Most recent order placed by the customer.
        MAX(o.order_date) AS last_order_date,

        -- First order placed by the customer.
        MIN(o.order_date) AS first_order_date

    FROM customers c

    INNER JOIN orders o
        ON c.customer_id = o.customer_id

    INNER JOIN order_details od
        ON o.order_id = od.order_id

    GROUP BY
        c.customer_id,
        c.company_name,
        c.country
)

SELECT
    customer_id,
    company_name,
    country,
    total_revenue,
    total_orders,
    first_order_date,
    last_order_date,

    -- Rank customers by total historical revenue.
    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS customer_rank

FROM customer_metrics

ORDER BY
    total_revenue DESC,
    company_name

LIMIT 10;